In [1]:
import torch
import numpy as np

# --- Task 1.1: Tạo Tensor (Như trong đề bài) ---
print("--- Task 1.1: Tạo Tensor ---")
# Tạo tensor từ list
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(f"Tensor từ list:\n {x_data}\n")

# Tạo tensor từ NumPy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(f"Tensor từ NumPy array:\n {x_np}\n")

# Tạo tensor với các giá trị ngẫu nhiên hoặc hằng số
x_ones = torch.ones_like(x_data) # tạo tensor gồm các số 1 có cùng shape với x_data
print(f"Ones Tensor:\n {x_ones}\n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # tạo tensor ngẫu nhiên
print(f"Random Tensor:\n {x_rand}\n")

# In ra shape, dtype, và device của tensor
print(f"Shape của tensor: {x_rand.shape}")
print(f"Datatype của tensor: {x_rand.dtype}")
print(f"Device lưu trữ tensor: {x_rand.device}\n")


# --- Task 1.2: Các phép toán trên Tensor ---
print("--- Task 1.2: Các phép toán ---")

# 1. Cộng x_data với chính nó
sum_tensor = x_data + x_data
print(f"Cộng x_data với chính nó:\n {sum_tensor}\n")

# 2. Nhân x_data với 5
mul_tensor = x_data * 5
print(f"Nhân x_data với 5:\n {mul_tensor}\n")

# 3. Nhân ma trận x_data với x_data.T
# x_data.T là ma trận chuyển vị của x_data
transpose_tensor = x_data.T
matmul_tensor = x_data @ transpose_tensor
print(f"Nhân ma trận x_data với x_data.T:\n {matmul_tensor}\n")


# --- Task 1.3: Indexing và Slicing ---
print("--- Task 1.3: Indexing và Slicing ---")

# 1. Lấy ra hàng đầu tiên
first_row = x_data[0] # Hoặc x_data[0, :]
print(f"Hàng đầu tiên:\n {first_row}\n")

# 2. Lấy ra cột thứ hai (index 1)
second_col = x_data[:, 1]
print(f"Cột thứ hai:\n {second_col}\n")

# 3. Lấy ra giá trị ở hàng thứ hai (index 1), cột thứ hai (index 1)
element_1_1 = x_data[1, 1]
print(f"Giá trị (hàng 2, cột 2): {element_1_1}\n")


# --- Task 1.4: Thay đổi hình dạng Tensor ---
print("--- Task 1.4: Thay đổi hình dạng ---")

# Tạo một tensor có shape (4, 4)
tensor_4x4 = torch.rand(4, 4)
print(f"Tensor (4, 4) ban đầu:\n {tensor_4x4}\n")

# Sử dụng view để biến nó thành (16, 1)
# .view() và .reshape() khá tương đồng, .view() yêu cầu dữ liệu phải liền mạch trong bộ nhớ
tensor_16x1 = tensor_4x4.view(16, 1)
print(f"Tensor (16, 1) sau khi view:\n {tensor_16x1}\n")
print(f"Shape mới: {tensor_16x1.shape}")

--- Task 1.1: Tạo Tensor ---
Tensor từ list:
 tensor([[1, 2],
        [3, 4]])

Tensor từ NumPy array:
 tensor([[1, 2],
        [3, 4]])

Ones Tensor:
 tensor([[1, 1],
        [1, 1]])

Random Tensor:
 tensor([[0.3060, 0.9406],
        [0.3201, 0.8320]])

Shape của tensor: torch.Size([2, 2])
Datatype của tensor: torch.float32
Device lưu trữ tensor: cpu

--- Task 1.2: Các phép toán ---
Cộng x_data với chính nó:
 tensor([[2, 4],
        [6, 8]])

Nhân x_data với 5:
 tensor([[ 5, 10],
        [15, 20]])

Nhân ma trận x_data với x_data.T:
 tensor([[ 5, 11],
        [11, 25]])

--- Task 1.3: Indexing và Slicing ---
Hàng đầu tiên:
 tensor([1, 2])

Cột thứ hai:
 tensor([2, 4])

Giá trị (hàng 2, cột 2): 4

--- Task 1.4: Thay đổi hình dạng ---
Tensor (4, 4) ban đầu:
 tensor([[0.4326, 0.0087, 0.0652, 0.2222],
        [0.9713, 0.5409, 0.7011, 0.4730],
        [0.5349, 0.2061, 0.2358, 0.1998],
        [0.5024, 0.5517, 0.2806, 0.2013]])

Tensor (16, 1) sau khi view:
 tensor([[0.4326],
        [0.00

In [2]:
import torch

# --- Task 2.1: Thực hành với autograd ---
print("--- Task 2.1: Thực hành với autograd ---")

# Tạo một tensor và yêu cầu tính đạo hàm cho nó
x = torch.ones(1, requires_grad=True)
print(f"x: {x}")

# Thực hiện một phép toán
y = x + 2
print(f"y: {y}")

# y được tạo ra từ một phép toán có x, nên nó cũng có grad_fn
print(f"grad_fn của y: {y.grad_fn}")

# Thực hiện thêm các phép toán
z = y * y * 3
print(f"z: {z}")

# Tính đạo hàm của z theo x
print("Đang gọi z.backward() lần 1...")
z.backward() # tương đương z.backward(torch.tensor(1.))

# Đạo hàm được lưu trong thuộc tính .grad
# Ta có z = 3 * (x+2)^2 => dz/dx = 6 * (x+2). Với x=1, dz/dx = 18
print(f"Đạo hàm của z theo x (lần 1): {x.grad}")

print("\n--- Thử gọi z.backward() lần 2 ---")
try:
    z.backward()
except RuntimeError as e:
    print(f"Lỗi xảy ra khi gọi backward() lần 2:\n {e}")

--- Task 2.1: Thực hành với autograd ---
x: tensor([1.], requires_grad=True)
y: tensor([3.], grad_fn=<AddBackward0>)
grad_fn của y: <AddBackward0 object at 0x00000197E4BE7B20>
z: tensor([27.], grad_fn=<MulBackward0>)
Đang gọi z.backward() lần 1...
Đạo hàm của z theo x (lần 1): tensor([18.])

--- Thử gọi z.backward() lần 2 ---
Lỗi xảy ra khi gọi backward() lần 2:
 Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.


In [3]:
import torch
from torch import nn

# --- Task 3.1: Lớp nn.Linear ---
print("--- Task 3.1: Lớp nn.Linear ---")
# Khởi tạo một lớp Linear biến đổi từ 5 chiều -> 2 chiều
linear_layer = torch.nn.Linear(in_features=5, out_features=2)

# Tạo một tensor đầu vào mẫu
input_tensor = torch.randn(3, 5) # 3 mẫu, mỗi mẫu 5 chiều

# Truyền đầu vào qua lớp linear
output = linear_layer(input_tensor)
print(f"Input shape (Linear): {input_tensor.shape}")
print(f"Output shape (Linear): {output.shape}")
print(f"Output (Linear):\n {output}\n")


# --- Task 3.2: Lớp nn.Embedding ---
print("--- Task 3.2: Lớp nn.Embedding ---")
# Khởi tạo lớp Embedding cho một từ điển 10 từ, mỗi từ biểu diễn bằng vector 3 chiều
embedding_layer = torch.nn.Embedding(num_embeddings=10, embedding_dim=3)

# Tạo một tensor đầu vào chứa các chỉ số của từ (ví dụ: một câu)
# Các chỉ số phải nhỏ hơn 10
input_indices = torch.LongTensor([1, 5, 0, 8])

# Lấy ra các vector embedding tương ứng
embeddings = embedding_layer(input_indices)
print(f"Input shape (Embedding): {input_indices.shape}")
print(f"Output shape (Embedding): {embeddings.shape}")
print(f"Embeddings:\n {embeddings}\n")


# --- Task 3.3: Kết hợp thành một nn.Module ---
print("--- Task 3.3: Kết hợp thành một nn.Module ---")

class MyFirstModel(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, output_dim):
        super(MyFirstModel, self).__init__()
        # Định nghĩa các lớp (layer) bạn sẽ dùng
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.linear = nn.Linear(embedding_dim, hidden_dim)
        self.activation = nn.ReLU() # Hàm kích hoạt
        self.output_layer = nn.Linear(hidden_dim, output_dim)

    def forward(self, indices):
        # Định nghĩa luồng dữ liệu đi qua các lớp
        
        # 1. Lấy embedding
        # Input indices shape: (batch_size, seq_len)
        # Output embeds shape: (batch_size, seq_len, embedding_dim)
        embeds = self.embedding(indices)
        
        # 2. Truyền qua lớp linear và hàm kích hoạt
        # Output hidden shape: (batch_size, seq_len, hidden_dim)
        hidden = self.activation(self.linear(embeds))
        
        # 3. Truyền qua lớp output
        # Output output shape: (batch_size, seq_len, output_dim)
        output = self.output_layer(hidden)
        
        return output

# Khởi tạo và kiểm tra mô hình
model = MyFirstModel(vocab_size=100, embedding_dim=16, hidden_dim=8, output_dim=2)

# Input: 1 batch, 1 câu gồm 4 từ
input_data = torch.LongTensor([[1, 2, 5, 9]]) 
print(f"Model input shape: {input_data.shape}")

# Chạy mô hình
output_data = model(input_data)

print(f"Model output shape: {output_data.shape}")
print(f"Model output (sample):\n {output_data}")

--- Task 3.1: Lớp nn.Linear ---
Input shape (Linear): torch.Size([3, 5])
Output shape (Linear): torch.Size([3, 2])
Output (Linear):
 tensor([[-0.4182,  0.1468],
        [ 0.4234,  0.3472],
        [-0.4937,  0.0137]], grad_fn=<AddmmBackward0>)

--- Task 3.2: Lớp nn.Embedding ---
Input shape (Embedding): torch.Size([4])
Output shape (Embedding): torch.Size([4, 3])
Embeddings:
 tensor([[ 0.5441,  0.3454,  0.3232],
        [ 0.5758, -0.3957, -1.0751],
        [ 0.5931,  1.1384,  1.0332],
        [-0.2861, -0.6040, -0.7976]], grad_fn=<EmbeddingBackward0>)

--- Task 3.3: Kết hợp thành một nn.Module ---
Model input shape: torch.Size([1, 4])
Model output shape: torch.Size([1, 4, 2])
Model output (sample):
 tensor([[[-0.1394,  0.2447],
         [ 0.1221,  0.1820],
         [ 0.3325,  0.1082],
         [-0.0816,  0.2725]]], grad_fn=<ViewBackward0>)
